'use client';
import { useParams } from 'next/navigation';

import CommunityLayout from '@/components/community-layout';
import Layout from '@/components/layout';

const Community = () => {
  const { userId } = useParams();
  return (
    <Layout title='Community' back={false} hasTopNav={true} hasTabBar={true}>
      <CommunityLayout>
        <div>{userId}</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>ㅍ <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div> <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
        <div>안녕</div>
      </CommunityLayout>
    </Layout>
  );
};
export default Community;
